### ISSUE TITLE
How to power on insta 360 one x2 from ubuntu machine

### ISSUE THREAD

**Issue by takerfume** [Insta360Develop/CameraSDK-Cpp#6]
I placed jetson nano connected to insta 360 one x2 in the remote place.

I would like to do this step.
1. enter jetson nano by ssh
2. power on one x2
3. transfer data from one x2 to jetson nano. 
I think x2 should be powered on in order to get data, so I would like to power on one x2.

Is there any way to turn one x2 on by command or program executed on jetson nano or other ubuntu machine?

**Comment by sladecraven** [comment]
Interested also, but now it is not possible with the current firmware

**Comment by tigerDZ** [comment]
Is that possible NOW？ @sladecraven @takerfume

**Comment by sladecraven** [comment]
Yes, since release of yesterday.

Let's imagine you have a "compendium folder" named "Bestiary" and you want to translate this title.

In your JSON language  file (ie fr.json, de.json, it.json, etc, etc), you have to declare (example in French) : 
```
....
"Bestiary": "Bestiaire"
....
```

Refresh and you will see the result.

PS : Sometimes, it seems that CompendiumFolders keep a kind of cache or something. If you do not see the translation after a refresh, start/stop the world.

**Comment by takerfume** [comment]
That's great news!

**Comment by victoriastraberg** [comment]
@LeRatierBretonnien Hi! Im using the Rock 4 SE (ubuntu) for the CameraSDK. How can I power on my Insta ONE x2 from my ubuntu machine?

**Comment by Ben93kie** [comment]
I did not understand @LeRatierBretonnien's comment (is it meant for another repo?).
Want to start up the X3 remotely (either Linux or Windows).

**Comment by Tianweihaihaihai** [comment]
cannot power on camera via sdk
